### ISSUE TITLE
Fatal error after login

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-audit#4]
ive get the following error after i try to login (until last friday all was working fine, and no changes over the weekend excluding sheduled backup of icinga2 vm)
Error: 
Fatal error: Declaration of Icinga\Module\Audit\ProvidedHook\AuditLog::logMessage($type, $message, array $data = NULL) must be compatible with Icinga\Application\Hook\AuditHook::logMessage($time, $identity, $type, $message, array $data = NULL) in /usr/share/icingaweb2/modules/audit/library/Audit/ProvidedHook/AuditLog.php on line 0

After disabling the audit modul in CLI the login works fine again, after the session auth was working now i re enabled the audit modul in CLI. by now still all is fine.

this problem is reproduceable each time when the session gets a timeout and i relogin the same error cames again.
so i disabled the audit modul via cli. now all is fine. but the auditing doesnt works again.

My Version:
Icinga2 v.2.9.0.1
IcingaWeb2 v.2.6.0
Icinga Audit v1.0.0
Director: v1.5.0
OS: Ubuntu 16.04

**Comment by lippserd** [comment]
Hi,

Thanks for the report. It seems that you did not update the module after upgrading Icinga Web 2 to version 2.6.0. If you still have problems, please open a new issue. I'll close this one.

Best,
Eric
