### ISSUE TITLE
IcingaWeb2 - Display of Audit-Log fields wrong

### ISSUE THREAD

**Issue by McBane87** [Icinga/icingaweb2-module-audit#5]
in IcingaWeb2 "System -> Audit Log" the fields are not getting displayed correctly from the log file, because the regex in "LogController.php" is incomplete. 
This line, for example, doesn't get splitted correctly:

```2019-01-03T10:04:39+01:00 - bob@a-blub.com - monitoring/command - Issued command actions/remove-downtime with the following payload: {"downtime":"ABC12345!f519ef33-9b9c-49cc-8c29-cccc369cd9ea"}```

But if I change the regex like this, it is working:

```patch
--- application/controllers/LogController.php  2018-07-19 10:02:09.000000000 +0200
+++ application/controllers/LogController.php       2019-01-03 14:13:41.461248308 +0100
@@ -35,8 +35,8 @@
             'filename'  => $file,
             'fields'    => '/(?<!.)(?<datetime>[0-9]{4}(?:-[0-9]{2}){2}'    // date
                 . 'T[0-9]{2}(?::[0-9]{2}){2}(?:[\+\-][0-9]{2}:[0-9]{2})?)'  // time
-                . ' - (?<identity>.*)'                                      // identity
-                . ' - (?<type>[A-Za-z]+)'                                   // type
+                . ' - (?<identity>.*?)'                                      // identity
+                . ' - (?<type>[A-Za-z\/]+)'                                   // type
                 . ' - (?<message>.*)(?!.)/msS'                              // message
         ]));
 
```

Please note the "?" at the end of the "identity" regex-part and the "\/" inside the "type" regex-part

**Comment by n0braist** [comment]
Hi, I had the same problem but used 
`. ' - (?<type>.*)'                                   // type`
